### PR TITLE
(WIP) Fix firefox tests

### PR DESCRIPTION
**Pull request by OmarIthawi**
#28 tests are failing. This is a vein attempt to fix those tests.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-3775](https://openedx.atlassian.net/browse/OSPR-3775) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@OmarIthawi Thank you for your contribution. @jmbowman Can you give this a look when you have a chance?

**Comment by jmbowman** [comment]
@OmarIthawi Do you want help or review on this yet, or do you want more time to sort out the test failures?

**Comment by OmarIthawi** [comment]
@jmbowman I'm actually stuck and this is just a vein attempt from me to fix. I've sort of gave up on since I don't have much idea how to proceed further.

I'd appreciate any help from you with this.

**Comment by OmarIthawi** [comment]
@jmbowman because I'm not going to be able to fix the issue, I'll close the PR for now.

**Pull request closed without merging**
