### PR TITLE
(WIP) Fix tests after Travis CI Xenial upgrade

### LINKED ISSUE #32: `test_const.TEST_IMAGE_URL` is not working and breaking the tests
Correct, those 2 links still work; the one that doesn't is https://docs.google.com/drawings/d/1lmmxboBM5c_0WCTjhAxBdkpqQb3T8VSwtuG0TRR1ODQ/pub?w=960&h=720 (`google_drive.tests.test_const.TEST_IMAGE_URL`).

_Originally posted by @jmbowman in https://github.com/edx-solutions/xblock-google-drive/pull/31#issuecomment-524871887_

### PR DESCRIPTION
**Pull request by OmarIthawi**
Same as #31 but also addresses #32 

> The bulk of the broken tests were due to Travis [changing how xvfb works](https://benlimmer.com/2019/01/14/travis-ci-xvfb/) when they switched the default test runner to Xenial. I updated the tests to use headless Firefox instead, so we don't even need xvfb now.
> 
> Also dropping tests for no-longer-supported Django versions.

In addition to @jmbowman's fix, I've done the following to address #32:

## Problem with Image URL
For some reasons the old link for `TEST_IMAGE_URL` is now not accessible and breaking the tests. 

## Solution
To solve the issue I've created a new [Google Drawing (link)](https://docs.google.com/drawings/d/1Ax2dQZjuhj9T5kqN9-nl1JsyEdfGqeMcqPHnVF6uDkY/edit) and added the following as contributors:
 
 - `oscm at edx.org` as editor
 - `@nedbat` as editor
 - @jmbowman as editor
 - `nate at appsembler.com` (@appsembler CEO) as owner, one more method against deletion

I've also added an annoying warning so people will less likely delete it:

<kbd></kbd>

## Related Issues and Pull Requests

Closes #31 
Fixes #32

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-3816](https://openedx.atlassian.net/browse/OSPR-3816) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by OmarIthawi** [comment]
Ok, apparently this is trick have not fixed the issue. I'm going to try with another method soon.

**Comment by natabene** [comment]
@OmarIthawi Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by OmarIthawi** [comment]
@jmbowman @natabene I don't think that I fully understand the issue that I'm trying to solve.

I'll close this pull request but keep the [Google Drawing](https://docs.google.com/drawings/d/1Ax2dQZjuhj9T5kqN9-nl1JsyEdfGqeMcqPHnVF6uDkY/edit) for now.

**Pull request closed without merging**
