### PR TITLE
Add French (Canada) to the languages list + updated the languages.

### PR DESCRIPTION
**Pull request by OmarIthawi**
As described.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-3764](https://openedx.atlassian.net/browse/OSPR-3764) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@OmarIthawi Thanks for your contribution. Will you need edX review for this?

**Comment by OmarIthawi** [comment]
Thanks @natabene, and yes please. I do need some one from edX to review it, since I don't have access to do anything here other than to make a pull request.

**Comment by natabene** [comment]
@jmbowman I think you worked in this repo, can you give it a look once you are back?

**Comment by natabene** [comment]
@OmarIthawi Can you work on the failing Travis test meanwhile?

**Comment by OmarIthawi** [comment]
Thanks @natabene. I saw the failed tests but I have no idea where to start.

I looks like this repo has not been updated and I think it's just an environment change that made the error to show up.

@jmbowman what do you think?

**Comment by OmarIthawi** [comment]
@natabene Unfortunately, this pull request is not going to be merged soon. It has a broken tests and I cannot fix them.

I'll have to close it and raise a :white_flag: 

cc: @jmbowman

**Pull request closed without merging**
