### PR TITLE
Fix tests after Travis CI Xenial upgrade

### PR DESCRIPTION
**Pull request by jmbowman**
The bulk of the broken tests were due to Travis [changing how xvfb works](https://benlimmer.com/2019/01/14/travis-ci-xvfb/) when they switched the default test runner to Xenial.  I updated the tests to use headless Firefox instead, so we don't even need xvfb now.

Also dropping tests for no-longer-supported Django versions.

### CODE REVIEW

**Comment by jmbowman** [comment]
@OmarIthawi In this PR I have the Firefox tests running again and mostly passing.  There are still 2 failures, apparently because the referenced Google Docs image no longer exists.

@georgebabey Are you up for figuring out (or delegating) creation of a new drawing that's less likely to vanish on us again due to account deactivation, etc.?  Also, this repo still needs to be updated to check Python 3 support.

**Comment by OmarIthawi** [comment]
Thanks @jmbowman for your help!

**Comment by OmarIthawi** [comment]
@jmbowman @georgebabey I'd like to let you know that I've checked both URLs and it works ok:

 - https://docs.google.com/presentation/d/1x2ZuzqHsMoh1epK8VsGAlanSo7r9z55ualwQlj-ofBQ/embed?start=true&loop=true&delayms=10000&slide=id.g4481a992f_035
 - https://calendar.google.com/calendar/embed?mode=Month&src=edx.org_lom804qe3ttspplj1bgeu1l3ak@group.calendar.google.com&showCalendars=0

cc: @natabene

**Comment by OmarIthawi** [comment]
@natabene could you please close this PR? It's no longer needed since https://github.com/edx-solutions/xblock-google-drive/pull/35.

**Pull request closed without merging**
