### PR TITLE
Add French (Canada) to the languages list + i18n update

### PR DESCRIPTION
**Pull request by OmarIthawi**
As described. Reopen of #28.

We should be using tags and version this repository. I've bumped the version for that.

### TODO

 - [x] Wait for #37 to get merged.

### CODE REVIEW

**Comment by OmarIthawi** [comment]
@natabene Could you please line this up for review? Also, owning this repository?

**Comment by natabene** [comment]
@shafqatfarhan @hasnain-naveed Could you please review and merge if this looks good?

**Comment by natabene** [comment]
@OmarIthawi Thank you for your contribution, we will look into this!

**Comment by OmarIthawi** [comment]
@natabene now we have #37 merged! This pull request have been reduced to become a basic translations update pull request. 

As far as I know it should be safe to merge even without an additional engineering review.

**Comment by natabene** [comment]
@OmarIthawi Thank you! @shafqatfarhan Our team owns this repo, can you give it a look and merge if you are ok with the change?

**Comment by hasnain-naveed** [comment]
@OmarIthawi Can you please tell me why did you delete the `en` and `eo` language's .mo file? And please squash the commits?

**Comment by OmarIthawi** [comment]
Thanks @hasnain-naveed. I'll follow up shortly.

**Comment by OmarIthawi** [comment]
Thanks @hasnain-naveed for the review.

> @OmarIthawi Can you please tell me why did you delete the `en` and `eo` language's .mo file?

It's not deleted. GitHub shows a lot of size reduction diff for the binary file which appears as if it's been deleted. Checking on the file system ([and on github](https://github.com/appsembler/xblock-google-drive/blob/i18n-bot/2019-07-27-161242/google_drive/translations/eo/LC_MESSAGES/text.mo)) shows that it's not been deleted:

```
$ ls -lah google_drive/translations/*/LC_MESSAGES/text.*
-rw------- 1 omar omar  337 Jan 12 12:38 google_drive/translations/en/LC_MESSAGES/text.mo
-rw------- 1 omar omar 3.6K Nov 17 16:58 google_drive/translations/en/LC_MESSAGES/text.po
-rw------- 1 omar omar 5.9K Jan 12 12:38 google_drive/translations/eo/LC_MESSAGES/text.mo
-rw------- 1 omar omar 7.8K Nov 17 16:58 google_drive/translations/eo/LC_MESSAGES/text.po
-rw------- 1 omar omar 3.0K Jan 12 12:38 google_drive/translations/es_419/LC_MESSAGES/text.mo
-rw------- 1 omar omar 5.1K Jan 12 12:38 google_drive/translations/es_419/LC_MESSAGES/text.po
-rw------- 1 omar omar 2.9K Jan 12 12:38 google_drive/translations/fr_CA/LC_MESSAGES/text.mo
-rw------- 1 omar omar 5.0K Jan 12 12:38 google_drive/translations/fr_CA/LC_MESSAGES/text.po
-rw------- 1 omar omar 3.1K Jan 12 12:38 google_drive/translations/ja_JP/LC_MESSAGES/text.mo
-rw------- 1 omar omar 5.3K Jan 12 12:38 google_drive/translations/ja_JP/LC_MESSAGES/text.po
```

The English file contains no translations so it makes sense to have it only few kilobytes.

> And please squash the commits?

Done. Now all update translations commits are combined. I've left the other ones to keep them atomic.

**Review by hasnain-naveed — APPROVED** [review]
LGTM 👍

**Comment by OmarIthawi** [comment]
Thanks @hasnain-naveed and @natabene. Could either of you merge this pull request so we tag the new release?

**Comment by natabene** [comment]
@hasnain-naveed Please merge.

**Pull request merged**
